config/routes.rb
Rails.application.routes.draw do
  resources :games

  root 'games#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many  :shots, validate: true, dependent: :destroy
  validates :players, numericality: { greater_than: 0, less_than: 5 }
  accepts_nested_attributes_for :shots
end

app/models/shot.rb
class Shot < ApplicationRecord
  belongs_to :game
  validates :number, :frame, :player, :pins, numericality: true
  validate :number_of_pins

  def number_of_pins
    current_pins = pins.to_i
    if current_pins > 10
      errors.add(:pins, "can't be more than 10")
    elsif current_pins < 0
        errors.add(:pins, "cannot be less than zero")
    elsif frame < 10
      shots = current_player_frame
      existing_pins = shots.map(&:pins).reduce(0, :+)
      if (existing_pins + current_pins) > 10
        max = 10 - existing_pins
        errors.add(:pins, "can't be more than #{max}")
      end
    else
      shots = current_player_frame
      if shots.size > 1 && shots[0].pins < 10
        if (shots[0].pins + shots[1].pins) > 10
          errors.add(:pins, "can't be more than 10")
        end
      end
    end
  end

  private
  def current_player_frame
    Shot.where(game: game,
               player: player,
               frame: frame).order(:number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
    @shot = @game.shots.build
    @scoreboard = ScoreCalculator.new(@game)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        session[:frame] = session[:player] = session[:shot_number] = 1
        session[:game_over] = session[:strike] = session[:spare] = false
        format.html { redirect_to @game, notice: 'Welcome. Enjoy your game!' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        @scoreboard = ScoreCalculator.new(@game)
        last_shot    = @game.shots.last
        current_game = ::MainLogic.new(@game, session)
        current_game.update(last_shot)
        session.merge!(current_game.status)

        format.html { redirect_to @game, notice: 'Scores updated successfully.' }
        format.json { render :show, status: :ok, location: @game }
      else
        @shot = @game.shots.last
        @scoreboard = ScoreCalculator.new(@game)
        format.js { render 'errors' }
        format.html { render :show, alert: 'Scores were not successfully updated.' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game destroyed successfully.' }
      format.json { head :no_content }
    end
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:players, shots_attributes: [:number, :frame, :player, :pins])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end

    flash_messages.join("\n").html_safe
  end

  def error_messages(messages)
     flash_messages = messages.map do |message|
      "<script>toastr.error('#{escape_javascript message}');</script>"
    end
    flash_messages.join("\n").html_safe
  end

  def strike_spare_total_format(total, first_shot)
    score = ''
    if total.to_i == 0 && (first_shot.to_i > 0 || first_shot == 'x')
      score = "-"
    else
      score = total
    end
    score
  end
end

app/views/games/_form.html.erb
<%= form_for(game) do |f|%>
  <div class="field form-group mt-4">
    <%= f.label :players, class: 'sr-only' %>
    <%= f.number_field :players , class: 'form-control', placeholder: 'Enter number of players' %>
  </div>

  <div class="actions form-group float-right">
    <%= f.submit "Start", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/games/_new_shot.html.erb
<div id='shot-form'>
  <%= form_for(@game, remote: true, authenticity_token: true, html: { class: 'form-inline'}) do |f| %>
    <%= f.fields_for :shots, @shot do |shot| %>
      <% if @shot.errors.any? %>
        <%= error_messages(@shot.errors.full_messages) %>
      <% end %>
      <%= shot.hidden_field :player, value: session[:player] %>
      <%= shot.hidden_field :frame, value: session[:frame] %>
      <%= shot.hidden_field :number, value: session[:shot_number] %>
      <div class='row'>
        <div class='col-md-6'>
          <div class="field form-group">
            <%= shot.label :pins, "Score:", class: 'sr-only' %>
            <%= shot.number_field :pins, class: 'form-control form-control', placeholder: 'Pins down' %>
          </div>
        </div>
        <div class="col-md-6 text-right">
          <%= f.submit "Shot", class: 'btn btn-info' %>
        </div>
      </div>
    <% end %>

  <% end %>
</div>

app/views/games/_score_table.html.erb
<div class='table-responsive'>
  <table class='table table-hover'>
    <thead class="thead-dark">
      <tr>
        <th>Frame</th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>10</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      <% @scoreboard.scoreboard.each_with_index do |row, i| %>
        <tr>
          <th>
            <div>Player: <%= i+1 %></div>
            <div>Shot 1</div>
            <div>Shot 2</div>
          </th>
        <% row[1..10].each do |cell| %>
          <td>
            <b><%= strike_spare_total_format(@scoreboard.total_for_frame(cell), @scoreboard.first_shot(cell)) %></b>
            <div><%= @scoreboard.first_shot(cell) %></div>
            <div><%= @scoreboard.second_shot(cell) %></div>
            <div><%= @scoreboard.third_shot(cell) %></div>
          </td>
        <% end %>
        <td>
          <%= @scoreboard.grand_total(row) %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/errors.js.erb
$('form').replaceWith('<%= j(render partial: 'new_shot') %>');

app/views/games/index.html.erb
<h1>Game List</h1>


<table class="table table-responsive">
  <thead>
    <tr>
      <th>Players</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td width="30%"><%= game.players %></td>
        <td width="30%"><%= link_to 'Show', game %></td>
        <td width="30%"><%= link_to 'Delete', game_path(game.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Game', new_game_path, class: 'btn btn-info' %>

app/views/games/new.html.erb
<h1 class="text-center mt-5">Ten-pin bowling</h1>
<%= image_tag('bowling.jpg', width: '100%') %>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path, class: "btn btn-danger"%>

app/views/games/show.html.erb
<div class='card-success'><h1 class="text-success text-center">Bowling Score Board</h1></div>
<% if session[:strike] %>
    <div class='card-text'>
      <%= image_tag('strike.png', width: '300px', height: '250px') %>
    </div>
  <% elsif session[:spare] %>
    <div class='card-text'>
      <%= image_tag('spare.png', width: '300px', height: '250px') %>
    </div>
  <% elsif session[:game_over] %>
    <div class='card-text'>
      <%= image_tag('game_over.png', width: '100%', height: '250px') %>
    </div>
<% end %>

<%= render partial: 'new_shot' unless session[:game_over] %>
<%= render partial: 'score_table' %>

<%= link_to 'Game List', games_path, class: "btn btn-danger float-right" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TenPinBowling</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>